name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test
      - name: Run eslint
        run: pnpm lint
      - name: Run prettier
        run: pnpx prettier src/** tests/**
